// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYcJDUyT8sNeIKkBVmI4iVYmBER_zLlI',
    appId: '1:473014017277:web:6778bc78ab433150727294',
    messagingSenderId: '473014017277',
    projectId: 'inventory-firebase-c4a0f',
    authDomain: 'inventory-firebase-c4a0f.firebaseapp.com',
    storageBucket: 'inventory-firebase-c4a0f.firebasestorage.app',
    measurementId: 'G-BXLDXCY4TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcsHcrt0rmgbwV_RBuvBYeDtLoQgBdg4',
    appId: '1:473014017277:android:ba6954b60ed7a503727294',
    messagingSenderId: '473014017277',
    projectId: 'inventory-firebase-c4a0f',
    storageBucket: 'inventory-firebase-c4a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TzfDpHhhpKG8GHeXxWQFonFZnxPI6Do',
    appId: '1:473014017277:ios:1819a6ff33a58992727294',
    messagingSenderId: '473014017277',
    projectId: 'inventory-firebase-c4a0f',
    storageBucket: 'inventory-firebase-c4a0f.firebasestorage.app',
    iosBundleId: 'com.example.inventoryFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3TzfDpHhhpKG8GHeXxWQFonFZnxPI6Do',
    appId: '1:473014017277:ios:1819a6ff33a58992727294',
    messagingSenderId: '473014017277',
    projectId: 'inventory-firebase-c4a0f',
    storageBucket: 'inventory-firebase-c4a0f.firebasestorage.app',
    iosBundleId: 'com.example.inventoryFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpYcJDUyT8sNeIKkBVmI4iVYmBER_zLlI',
    appId: '1:473014017277:web:9e66acf28edd528f727294',
    messagingSenderId: '473014017277',
    projectId: 'inventory-firebase-c4a0f',
    authDomain: 'inventory-firebase-c4a0f.firebaseapp.com',
    storageBucket: 'inventory-firebase-c4a0f.firebasestorage.app',
    measurementId: 'G-CD0PBHXGWR',
  );
}
